### ISSUE TITLE
[doc] Add docs on authentication

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#45] opened 2016-12-06 16:35 UTC
We use username\password\jwt, that worth to be documented in more details.

Push the docs at https://github.com/frictionlessdata/dpr-docs

Learn the mkdocs and create basic docs layout. See example at https://github.com/openspending/docs

**Comment by rufuspollock** [comment] 2017-01-10 16:01
DUPLICATE of https://github.com/frictionlessdata/dpr-api/issues/162

**Closed by rufuspollock** 2017-01-10 16:01 UTC
Labels: Doing next 24 hour

**Comment by Fak3** [comment] 2017-01-10 16:04
https://github.com/frictionlessdata/dpr-docs/pull/7
